const { contextBridge, ipcRenderer } = require('electron');

const on = (channel) => (fn) => ipcRenderer.on(channel, (_e, payload) => fn(payload));

contextBridge.exposeInMainWorld('api', {
  getSettings: () => ipcRenderer.invoke('settings:get'),
  setSettings: (s) => ipcRenderer.invoke('settings:set', s),
  listVoices: () => ipcRenderer.invoke('voices:list'),
  t3Status: () => ipcRenderer.invoke('t3:status'),
  t3Pair: (link) => ipcRenderer.invoke('t3:pair', link),
  t3Unpair: () => ipcRenderer.send('t3:unpair'),
  onT3: (fn) => ipcRenderer.on('t3', (_e, s) => fn(s)),
  saveVoice: (name, pcm) => ipcRenderer.invoke('voices:save', name, pcm),
  deleteVoice: (name) => ipcRenderer.invoke('voices:delete', name),
  channelState: () => ipcRenderer.invoke('channel:state'),
  sttOpen: () => ipcRenderer.send('stt:open'),
  sttClose: () => ipcRenderer.send('stt:close'),
  sttAudio: (pcm) => ipcRenderer.send('stt:audio', pcm),
  sttClear: () => ipcRenderer.send('stt:clear'),
  sttCommit: () => ipcRenderer.send('stt:commit'),
  ttsStop: () => ipcRenderer.send('tts:stop'),
  ttsTest: () => ipcRenderer.send('tts:test'),
  ttsSay: (text) => ipcRenderer.send('tts:say', text),
  send: (msg) => ipcRenderer.invoke('send', msg),
  setContext: (text) => ipcRenderer.send('context:set', text),
  onContextSent: on('context:sent'),
  onChannel: on('channel'),
  onStt: on('stt'),
  onTts: on('tts'),
  onAudio: on('audio'),
  onPermission: on('permission'),
  onError: on('error'),
  onHotkey: on('hotkey'),
  onDelegated: on('delegated'),
  onActivity: on('activity'),
  uiReport: (state) => ipcRenderer.send('ui:report', state),
  onUiAction: on('ui:action'),
  liveCreate: (sdp) => ipcRenderer.invoke('live:create', sdp),
  liveEvent: (ev) => ipcRenderer.send('live:event', ev),
  onLiveConnect: on('live:connect'),
  onLiveSend: on('live:send'),
  onLiveDisconnect: on('live:disconnect'),
  // sub-agents panel
  agentsToggle: () => ipcRenderer.send('agents:toggle'),
  agentsClose: () => ipcRenderer.send('agents:close'),
  agentStop: (id) => ipcRenderer.send('agents:stop', id),
  agentsSummary: () => ipcRenderer.invoke('agents:summary'),
  onAgentsSummary: on('agents:summary'),
  onAgentsAll: on('agents:all'),
  onAgentUpdate: on('agents:update'),
  onAgentLog: on('agents:log'),
  // message history panel
  historyToggle: () => ipcRenderer.send('history:toggle'),
  pairInfo: () => ipcRenderer.invoke('pair:info'),
  historyClose: () => ipcRenderer.send('history:close'),
  historyClear: () => ipcRenderer.send('history:clear'),
  historySummary: () => ipcRenderer.invoke('history:summary'),
  onHistorySummary: on('history:summary'),
  onHistoryAll: on('history:all'),
  onHistoryAdd: on('history:add'),
  onHistorySettled: on('history:settled'),
  onHistoryActivity: on('history:activity'),
});
